name = "ExcelFiles"
uuid = "89b67f3b-d1aa-5f6f-9ca4-282e8d98620d"
version = "1.0.0"

[deps]
DataValues = "e7dc6d0d-1eca-5fa6-8ad6-5aecde8b7ea5"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
ExcelReaders = "c04bee98-12a5-510c-87df-2a230cb6e075"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
IterableTables = "1c8ee90f-4401-5389-894e-7a04a3dc0f4d"
IteratorInterfaceExtensions = "82899510-4779-5014-852e-03e436cf321d"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
TableShowUtils = "5e66a065-1f0a-5976-b372-e0b8c017ca10"
TableTraits = "3783bdb8-4a98-5b6b-af9a-565f29a5fe9c"
TableTraitsUtils = "382cd787-c1b6-5bf2-a167-d5b971a19bda"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
DataFrames = "≥ 0.14.1"
DataValues = "≥ 0.4.11"
ExcelReaders = "≥ 0.10.2"
FileIO = "≥ 1.0.0"
IterableTables = "≥ 0.8.3"
IteratorInterfaceExtensions = "^0.1.1, ^1"
PyCall = "≥ 1.90.0"
TableShowUtils = "≥ 0.1.1"
TableTraits = "^0.3.1, ^0.4, ^1"
TableTraitsUtils = "0.3, 0.4, 1"
XLSX = "≥ 0.4.1"
julia = "1"

[extras]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Dates", "Test", "DataFrames"]
